# Generated by Django 5.0.3 on 2024-09-27 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
