# Generated by Django 5.0.3 on 2024-09-27 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_journal_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journal',
            old_name='author',
            new_name='author_id',
        ),
    ]
