# Generated by Django 5.0.3 on 2024-09-23 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0002_song_music_uri'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='cover_image',
            field=models.ImageField(null=True, upload_to='song/'),
        ),
    ]
