# Generated by Django 5.0.3 on 2024-07-15 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='reader_count',
            field=models.IntegerField(default=0),
        ),
    ]
