# Generated by Django 5.0.3 on 2024-09-28 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0002_alter_story_reader_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='story/'),
        ),
    ]
