# Generated by Django 5.0.3 on 2024-07-25 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_managers_user_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role_id',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(default='Member', max_length=255),
        ),
    ]
